// Knight Impact Partners Organization Data
// Generated from: KIP Final Review Doc for Sol's Approval_.xlsx
// Date: February 13, 2024
// Total Organizations: 56
// Total Grants: 74
// Total Funding: $15,905,999

const KNIGHT_ORGANIZATIONS_DATA = [
  {
    "name": "Inner-City Muslim Action Network",
    "address": "2745 W. 63rd St",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60629",
    "category": "Community Building",
    "grant_amount_awarded": 2500000.0,
    "lat": 41.7787933,
    "lng": -87.6927225,
    "service_areas": [
      "chicago_lawn",
      "englewood"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 2,
    "primary_neighborhood": "Chicago Lawn, bordering Englewood",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 1000000.0,
        "category": "Growth Grant",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 2,
        "amount_awarded": 1500000.0,
        "category": "Growth Grant",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": null,
    "id": "inner-city_muslim_action_network",
    "city_category": "chicago"
  },
  {
    "name": "Greater Chicago Food Depository / City Colleges of Chicago Partnership",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Human Services",
    "grant_amount_awarded": 2100000.0,
    "lat": 41.885,
    "lng": -87.635,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 2100000.0,
        "category": "Growth Grant",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "greater_chicago_food_depository___city_colleges_of",
    "city_category": "chicago"
  },
  {
    "name": "City Colleges of Chicago Foundation",
    "address": "180 N Wabash",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60601",
    "category": "Education",
    "grant_amount_awarded": 1250000.0,
    "lat": 41.8854209,
    "lng": -87.6266822,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "##NOT_FOUND##",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 500000.0,
        "category": "Growth Grant",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 2,
        "amount_awarded": 750000.0,
        "category": "Growth Grant",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "Ste 200",
    "id": "city_colleges_of_chicago_foundation",
    "city_category": "chicago"
  },
  {
    "name": "Endeavor Health",
    "address": "1301 Central Street",
    "city": "Evanston",
    "state": "IL",
    "zip_code": "60201",
    "category": "Health",
    "grant_amount_awarded": 870999.0,
    "lat": 42.0647814,
    "lng": -87.6899555,
    "service_areas": [
      "evanston"
    ],
    "service_areas_type": "Evanston",
    "service_areas_count": 1,
    "primary_neighborhood": "60201",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 310500.0,
        "category": "Growth Grant",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 560499.0,
        "category": "Growth Grant",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": null,
    "id": "endeavor_health",
    "city_category": "chicago"
  },
  {
    "name": "La Casa Norte",
    "address": "3533 W North Ave.",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60647",
    "category": "Human Services",
    "grant_amount_awarded": 525000.0,
    "lat": 41.909739,
    "lng": -87.7155111,
    "service_areas": [
      "humboldt_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 175000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 300000.0,
        "category": "Capital ",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 3,
        "amount_awarded": 25000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      },
      {
        "number": 4,
        "amount_awarded": 25000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 4,
    "has_multiple_grants": true,
    "location_note": "Chicago, IL 60647",
    "id": "la_casa_norte",
    "city_category": "chicago"
  },
  {
    "name": "Neighborhood Capital Fund",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Community Building",
    "grant_amount_awarded": 500000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 500000.0,
        "category": "Capital ",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "neighborhood_capital_fund",
    "city_category": "chicago"
  },
  {
    "name": "Nourishing Hope",
    "address": "1716 W. Hubbard St.",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60622",
    "category": "Human Services",
    "grant_amount_awarded": 455000.0,
    "lat": 41.8900706,
    "lng": -87.6703806,
    "service_areas": [
      "west_town"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": "West Town",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 275000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 30000.0,
        "category": "Capacity & Leadership",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 3,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 3,
    "has_multiple_grants": true,
    "location_note": "--",
    "id": "nourishing_hope",
    "city_category": "chicago"
  },
  {
    "name": "Chicago Funders Together to End Homelessness",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 450000.0,
    "lat": 41.885,
    "lng": -87.635,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 300000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 150000.0,
        "category": "Systems Building",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": null,
    "id": "chicago_funders_together_to_end_homelessness",
    "city_category": "chicago"
  },
  {
    "name": "Cara Collective",
    "address": "237 South Desplaines",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60661",
    "category": "Human Services",
    "grant_amount_awarded": 400000.0,
    "lat": 41.878993,
    "lng": -87.6439224,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "West City-Wide Gate",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": ".",
    "id": "cara_collective",
    "city_category": "chicago"
  },
  {
    "name": "One Million Degrees",
    "address": "180 N Wabash",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60601",
    "category": "Education",
    "grant_amount_awarded": 400000.0,
    "lat": 41.8854209,
    "lng": -87.6266822,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "City-Wide, Chicago",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 2,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "Ste 415",
    "id": "one_million_degrees",
    "city_category": "chicago"
  },
  {
    "name": "Reclaiming Chicago",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Community Building",
    "grant_amount_awarded": 350000.0,
    "lat": 41.81,
    "lng": -87.7,
    "service_areas": [
      "riverdale",
      "armour_square",
      "lower_west_side",
      "chicago_lawn",
      "englewood",
      "clearing",
      "calumet_heights",
      "hegewisch",
      "gage_park",
      "south_chicago",
      "west_garfield_park",
      "greater_grand_crossing",
      "morgan_park",
      "fuller_park",
      "grand_boulevard",
      "near_west_side",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "garfield_ridge",
      "west_town",
      "west_lawn",
      "washington_park",
      "douglas",
      "south_lawndale",
      "mount_greenwood",
      "roseland",
      "austin",
      "woodlawn",
      "mckinley_park",
      "oakland",
      "north_lawndale",
      "kenwood",
      "west_englewood",
      "archer_heights",
      "washington_heights",
      "beverly",
      "hyde_park",
      "south_shore",
      "chatham",
      "west_pullman",
      "ashburn",
      "bridgeport",
      "west_elsdon",
      "humboldt_park",
      "brighton_park",
      "east_side",
      "burnside",
      "new_city",
      "pullman",
      "east_garfield_park"
    ],
    "service_areas_type": "South West Sides",
    "service_areas_count": 51,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 350000.0,
        "category": "Capital ",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "reclaiming_chicago",
    "city_category": "chicago"
  },
  {
    "name": "Hope Chicago",
    "address": "303 E Wacker Dr",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60601",
    "category": "Education",
    "grant_amount_awarded": 300000.0,
    "lat": 41.8876079,
    "lng": -87.6201786,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "##NOT_FOUND##",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 2,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "Ste 360",
    "id": "hope_chicago",
    "city_category": "chicago"
  },
  {
    "name": "Connections for the Homeless",
    "address": "2121 Dewey Ave",
    "city": "Evanston",
    "state": "IL",
    "zip_code": "60201",
    "category": "Human Services",
    "grant_amount_awarded": 300000.0,
    "lat": 42.0565866,
    "lng": -87.6955076,
    "service_areas": [
      "evanston"
    ],
    "service_areas_type": "Evanston",
    "service_areas_count": 1,
    "primary_neighborhood": "Evanston",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "Attn: Development",
    "id": "connections_for_the_homeless",
    "city_category": "chicago"
  },
  {
    "name": "MAAFA Redemption Project",
    "address": "22 N. Kildare Ave",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60624",
    "category": "Education",
    "grant_amount_awarded": 275000.0,
    "lat": 41.8815161,
    "lng": -87.7331635,
    "service_areas": [
      "west_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": "West Garfield Park",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Capital ",
        "quarter": "Q4-2024",
        "year": 2024
      },
      {
        "number": 2,
        "amount_awarded": 75000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "Suite 101",
    "id": "maafa_redemption_project",
    "city_category": "chicago"
  },
  {
    "name": "The Renaissance Collaborative",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Community Building",
    "grant_amount_awarded": 275000.0,
    "lat": 41.824,
    "lng": -87.613,
    "service_areas": [
      "douglas",
      "grand_boulevard"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 2,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 275000.0,
        "category": "Capital ",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "the_renaissance_collaborative",
    "city_category": "chicago"
  },
  {
    "name": "New Life Centers of Chicagoland, NFP",
    "address": "4101 W 51 ST",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60632",
    "category": "Human Services",
    "grant_amount_awarded": 250000.0,
    "lat": 41.843,
    "lng": -87.713,
    "service_areas": [
      "south_lawndale",
      "clearing",
      "humboldt_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 3,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 50000.0,
        "category": "Capacity & Leadership",
        "quarter": "Q4",
        "year": 2025
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": ".",
    "id": "new_life_centers_of_chicagoland_nfp",
    "city_category": "chicago"
  },
  {
    "name": "Erie Family Health Foundation",
    "address": "1701 W. Superior",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60622",
    "category": "Health",
    "grant_amount_awarded": 200000.0,
    "lat": 41.8948109,
    "lng": -87.6700552,
    "service_areas": [
      "west_town"
    ],
    "service_areas_type": "Evanston Mixed",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Third Floor",
    "id": "erie_family_health_foundation",
    "city_category": "chicago"
  },
  {
    "name": "Partnership for Safe and Peaceful Communities",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Human Services",
    "grant_amount_awarded": 200000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "partnership_for_safe_and_peaceful_communities",
    "city_category": "chicago"
  },
  {
    "name": "Thresholds",
    "address": "4101 N. Ravenswood Ave.",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60613",
    "category": "Human Services",
    "grant_amount_awarded": 200000.0,
    "lat": 41.9562193,
    "lng": -87.6734166,
    "service_areas": [
      "lincoln_square"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Capital ",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "thresholds",
    "city_category": "chicago"
  },
  {
    "name": "UChicago Inclusive Economy Lab",
    "address": "111 W Washington",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60602",
    "category": "Systems Building",
    "grant_amount_awarded": 200000.0,
    "lat": 41.8828895,
    "lng": -87.6314181,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "City-Wide",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Systems Building",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Suite 1023",
    "id": "uchicago_inclusive_economy_lab",
    "city_category": "chicago"
  },
  {
    "name": "YWCA Metropolitan Chicago",
    "address": "1 N LaSalle",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60602",
    "category": "Community Building",
    "grant_amount_awarded": 200000.0,
    "lat": 41.8860221,
    "lng": -87.6324027,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 200000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Suite 1700",
    "id": "ywca_metropolitan_chicago",
    "city_category": "chicago"
  },
  {
    "name": "BUILD, Inc.",
    "address": "5100 W. Harrison Street",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60644",
    "category": "Human Services",
    "grant_amount_awarded": 175000.0,
    "lat": 41.8733221,
    "lng": -87.7544433,
    "service_areas": [
      "austin"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 175000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Attn: Development",
    "id": "build_inc",
    "city_category": "chicago"
  },
  {
    "name": "Access Living",
    "address": "115 W. Chicago Ave",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60660",
    "category": "Human Services",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8965274,
    "lng": -87.6330221,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "River North",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "access_living",
    "city_category": "chicago"
  },
  {
    "name": "Breakthrough",
    "address": "402 N St. Louis Avenue",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60624",
    "category": "Community Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8884576,
    "lng": -87.7137763,
    "service_areas": [
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "breakthrough",
    "city_category": "chicago"
  },
  {
    "name": "Crossroads Fund",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Systems Building",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "crossroads_fund",
    "city_category": "chicago"
  },
  {
    "name": "Forefront",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Systems Building",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "forefront",
    "city_category": "chicago"
  },
  {
    "name": "Greater Auburn Gresham Development Corporation",
    "address": "839 W. 79th Street",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60620",
    "category": "Community Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.7503856,
    "lng": -87.6457413,
    "service_areas": [
      "auburn_gresham"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Suite 400",
    "id": "greater_auburn_gresham_development_corporation",
    "city_category": "chicago"
  },
  {
    "name": "Inner-City Computer Stars",
    "address": "750 N Orleans",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60654",
    "category": "Education",
    "grant_amount_awarded": 150000.0,
    "lat": 41.895676,
    "lng": -87.637261,
    "service_areas": [
      "uptown",
      "chatham",
      "south_shore",
      "austin",
      "north_lawndale",
      "auburn_gresham",
      "rogers_park",
      "logan_square"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 8,
    "primary_neighborhood": "##NOT_FOUND##",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Suite 500",
    "id": "inner-city_computer_stars",
    "city_category": "chicago"
  },
  {
    "name": "Latinos Progresando",
    "address": "2724 W Cermak Rd",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60608",
    "category": "Community Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8522013,
    "lng": -87.6940542,
    "service_areas": [
      "south_lawndale"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": "Marshall Square",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "latinos_progresando",
    "city_category": "chicago"
  },
  {
    "name": "Renaissance Social Services. Inc.",
    "address": "2501 W. Washington Blvd.",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60612",
    "category": "Human Services",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8828007,
    "lng": -87.6889283,
    "service_areas": [
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Suite 401",
    "id": "renaissance_social_services_inc",
    "city_category": "chicago"
  },
  {
    "name": "Revolution Workshop",
    "address": "3410 W Lake St",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60624",
    "category": "Education",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8847406,
    "lng": -87.7114906,
    "service_areas": [
      "roseland",
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 2,
    "primary_neighborhood": "East Garfield Park",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "revolution_workshop",
    "city_category": "chicago"
  },
  {
    "name": "The Resurrection Project",
    "address": "1818 S. Paulina St.",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60608",
    "category": "Community Building",
    "grant_amount_awarded": 150000.0,
    "lat": 41.8571182,
    "lng": -87.668953,
    "service_areas": [
      "lower_west_side"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": "Pilsen",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 150000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "the_resurrection_project",
    "city_category": "chicago"
  },
  {
    "name": "Covenant House Illinois",
    "address": "2934",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60612",
    "category": "Human Services",
    "grant_amount_awarded": 125000.0,
    "lat": 41.8957142,
    "lng": -87.6996248,
    "service_areas": [
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 125000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "W. Lake St",
    "id": "covenant_house_illinois",
    "city_category": "chicago"
  },
  {
    "name": "Franciscan Outreach",
    "address": "1101 W. Adams Street",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60607",
    "category": "Human Services",
    "grant_amount_awarded": 125000.0,
    "lat": 41.8787862,
    "lng": -87.6549505,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 125000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "suite A",
    "id": "franciscan_outreach",
    "city_category": "chicago"
  },
  {
    "name": "The Boulevard of Chicago, Inc.",
    "address": "3456 West Franklin Boulevard",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60624",
    "category": "Human Services",
    "grant_amount_awarded": 125000.0,
    "lat": 41.8906224,
    "lng": -87.7131003,
    "service_areas": [
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": "##NOT_FOUND##",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 125000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "---",
    "id": "the_boulevard_of_chicago_inc",
    "city_category": "chicago"
  },
  {
    "name": "AMPT",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 100000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Systems Building",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "ampt",
    "city_category": "chicago"
  },
  {
    "name": "Center on Halsted",
    "address": "3656 N. Halsted Street",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60613",
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.9488651,
    "lng": -87.6498854,
    "service_areas": [
      "riverdale",
      "armour_square",
      "calumet_heights",
      "hegewisch",
      "south_chicago",
      "greater_grand_crossing",
      "morgan_park",
      "fuller_park",
      "grand_boulevard",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "lake_view",
      "washington_park",
      "douglas",
      "mount_greenwood",
      "roseland",
      "woodlawn",
      "oakland",
      "kenwood",
      "washington_heights",
      "beverly",
      "hyde_park",
      "south_shore",
      "chatham",
      "west_pullman",
      "ashburn",
      "bridgeport",
      "east_side",
      "burnside",
      "pullman"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 31,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "center_on_halsted",
    "city_category": "chicago"
  },
  {
    "name": "Chicago South Side Birth Center",
    "address": "PO Box",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60643",
    "category": "Health",
    "grant_amount_awarded": 100000.0,
    "lat": 41.8,
    "lng": -87.62,
    "service_areas": [
      "chicago_lawn",
      "englewood",
      "clearing",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "greater_grand_crossing",
      "fuller_park",
      "grand_boulevard",
      "avalon_park",
      "south_deering",
      "garfield_ridge",
      "west_lawn",
      "washington_park",
      "douglas",
      "roseland",
      "woodlawn",
      "oakland",
      "kenwood",
      "west_englewood",
      "archer_heights",
      "hyde_park",
      "south_shore",
      "chatham",
      "west_elsdon",
      "brighton_park",
      "east_side",
      "burnside",
      "new_city",
      "pullman"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 30,
    "primary_neighborhood": "Beverly/Morgan Park",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "436913",
    "id": "chicago_south_side_birth_center",
    "city_category": "chicago"
  },
  {
    "name": "Erie Neighborhood House",
    "address": "1701 W Superior St",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60622",
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.8948109,
    "lng": -87.6700552,
    "service_areas": [
      "south_lawndale",
      "west_town"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 2,
    "primary_neighborhood": "West Town",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "erie_neighborhood_house",
    "city_category": "chicago"
  },
  {
    "name": "Imagine Englewood If",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Community Building",
    "grant_amount_awarded": 100000.0,
    "lat": 41.78,
    "lng": -87.645,
    "service_areas": [
      "englewood"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "imagine_englewood_if",
    "city_category": "chicago"
  },
  {
    "name": "Lyte Collective",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.7626,
    "lng": -87.6146,
    "service_areas": [
      "greater_grand_crossing"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": null,
    "id": "lyte_collective",
    "city_category": "chicago"
  },
  {
    "name": "Margaret\u2019s Village",
    "address": "7315 S Yale Ave",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60621",
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.7614301,
    "lng": -87.6307994,
    "service_areas": [
      "englewood"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "margaret\u2019s_village",
    "city_category": "chicago"
  },
  {
    "name": "New Moms, Inc.",
    "address": "New Moms",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60651",
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.8947,
    "lng": -87.765,
    "service_areas": [
      "austin"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "5317 W. Chicago Ave.",
    "id": "new_moms_inc",
    "city_category": "chicago"
  },
  {
    "name": "Small Moves Principal Emergency Fund",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Human Services",
    "grant_amount_awarded": 100000.0,
    "lat": 41.81,
    "lng": -87.7,
    "service_areas": [
      "riverdale",
      "armour_square",
      "lower_west_side",
      "chicago_lawn",
      "englewood",
      "clearing",
      "calumet_heights",
      "hegewisch",
      "gage_park",
      "south_chicago",
      "west_garfield_park",
      "greater_grand_crossing",
      "morgan_park",
      "fuller_park",
      "grand_boulevard",
      "near_west_side",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "garfield_ridge",
      "west_town",
      "west_lawn",
      "washington_park",
      "douglas",
      "south_lawndale",
      "mount_greenwood",
      "roseland",
      "austin",
      "woodlawn",
      "mckinley_park",
      "oakland",
      "north_lawndale",
      "kenwood",
      "west_englewood",
      "archer_heights",
      "washington_heights",
      "beverly",
      "hyde_park",
      "south_shore",
      "chatham",
      "west_pullman",
      "ashburn",
      "bridgeport",
      "west_elsdon",
      "humboldt_park",
      "brighton_park",
      "east_side",
      "burnside",
      "new_city",
      "pullman",
      "east_garfield_park"
    ],
    "service_areas_type": "South West Sides",
    "service_areas_count": 51,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q3",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "small_moves_principal_emergency_fund",
    "city_category": "chicago"
  },
  {
    "name": "Task Force Prevention and Community Services",
    "address": "9 N. Cicero Ave",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60644",
    "category": "Health",
    "grant_amount_awarded": 100000.0,
    "lat": 41.8806589,
    "lng": -87.7451743,
    "service_areas": [
      "austin"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 100000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "task_force_prevention_and_community_services",
    "city_category": "chicago"
  },
  {
    "name": "By The Hand Club For Kids",
    "address": "C/O By The Hand Club For Kids",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60644",
    "category": "Education",
    "grant_amount_awarded": 80000.0,
    "lat": 41.8947,
    "lng": -87.765,
    "service_areas": [
      "belmont_cragin",
      "riverdale",
      "hermosa",
      "austin",
      "near_north_side",
      "englewood"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 6,
    "primary_neighborhood": "Austin",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 30000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "415 N Laramie Ave",
    "id": "by_the_hand_club_for_kids",
    "city_category": "chicago"
  },
  {
    "name": "All Chicago Making Homelessness History",
    "address": "651 W Washington Blvd",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60661",
    "category": "Systems Building",
    "grant_amount_awarded": 75000.0,
    "lat": 41.8828975,
    "lng": -87.6444699,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 75000.0,
        "category": "Systems Building",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "# 504",
    "id": "all_chicago_making_homelessness_history",
    "city_category": "chicago"
  },
  {
    "name": "Chicago Coalition to End Homelessness",
    "address": "70 E Lake St",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60601",
    "category": "Systems Building",
    "grant_amount_awarded": 75000.0,
    "lat": 41.8872769,
    "lng": -87.7597981,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 75000.0,
        "category": "Systems Building",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Ste 720",
    "id": "chicago_coalition_to_end_homelessness",
    "city_category": "chicago"
  },
  {
    "name": "Xchange Chicago, Inc",
    "address": "7247 S. South Chicago Avenue",
    "city": "Chicago",
    "state": "Illinois",
    "zip_code": "60619",
    "category": "Community Building",
    "grant_amount_awarded": 75000.0,
    "lat": 41.7630641,
    "lng": -87.6015031,
    "service_areas": [
      "greater_grand_crossing"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 1,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 75000.0,
        "category": "Direct Program Services",
        "quarter": "Q1",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "Xchange Chicago",
    "id": "xchange_chicago_inc",
    "city_category": "chicago"
  },
  {
    "name": "Aids Foundation of Chicago",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 50000.0,
    "lat": 41.895,
    "lng": -87.635,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Systems Building ",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "aids_foundation_of_chicago",
    "city_category": "chicago"
  },
  {
    "name": "Civic Consulting Alliance",
    "address": "190 S LaSalle St.",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60603",
    "category": "Systems Building",
    "grant_amount_awarded": 50000.0,
    "lat": 41.8797583,
    "lng": -87.6326495,
    "service_areas": [
      "uptown",
      "chicago_lawn",
      "greater_grand_crossing",
      "morgan_park",
      "portage_park",
      "north_center",
      "avalon_park",
      "auburn_gresham",
      "south_deering",
      "west_lawn",
      "south_lawndale",
      "mount_greenwood",
      "lincoln_square",
      "dunning",
      "west_ridge",
      "ashburn",
      "humboldt_park",
      "riverdale",
      "englewood",
      "near_south_side",
      "edison_park",
      "lake_view",
      "jefferson_park",
      "washington_park",
      "edgewater",
      "mckinley_park",
      "north_lawndale",
      "oakland",
      "kenwood",
      "west_englewood",
      "washington_heights",
      "avondale",
      "beverly",
      "east_side",
      "lincoln_park",
      "norwood_park",
      "irving_park",
      "calumet_heights",
      "gage_park",
      "south_chicago",
      "grand_boulevard",
      "forest_glen",
      "west_town",
      "douglas",
      "roseland",
      "austin",
      "albany_park",
      "woodlawn",
      "hyde_park",
      "chatham",
      "west_elsdon",
      "bridgeport",
      "burnside",
      "pullman",
      "rogers_park",
      "east_garfield_park",
      "belmont_cragin",
      "armour_square",
      "lower_west_side",
      "near_north_side",
      "clearing",
      "hegewisch",
      "north_park",
      "logan_square",
      "west_garfield_park",
      "fuller_park",
      "montclare",
      "hermosa",
      "near_west_side",
      "loop",
      "ohare",
      "garfield_ridge",
      "archer_heights",
      "south_shore",
      "west_pullman",
      "brighton_park",
      "new_city"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": "The City-Wide",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 25000.0,
        "category": "Systems Building",
        "quarter": "Q4",
        "year": 2025
      },
      {
        "number": 2,
        "amount_awarded": 25000.0,
        "category": "Systems Building",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 2,
    "has_multiple_grants": true,
    "location_note": "39th Floor",
    "id": "civic_consulting_alliance",
    "city_category": "chicago"
  },
  {
    "name": "Alzheimer's Association",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Health",
    "grant_amount_awarded": 50000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "alzheimers_association",
    "city_category": "chicago"
  },
  {
    "name": "Diaper Equity Project",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Health",
    "grant_amount_awarded": 50000.0,
    "lat": 41.8781,
    "lng": -87.6298,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "State Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "diaper_equity_project",
    "city_category": "chicago"
  },
  {
    "name": "Kuumba Lynx",
    "address": "3524",
    "city": "Chicago",
    "state": "IL",
    "zip_code": "60624",
    "category": "Health",
    "grant_amount_awarded": 50000.0,
    "lat": 41.8956633,
    "lng": -87.7149332,
    "service_areas": [
      "west_garfield_park",
      "uptown",
      "east_garfield_park"
    ],
    "service_areas_type": "Specific",
    "service_areas_count": 3,
    "primary_neighborhood": "Garfield Park",
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Direct Program Services",
        "quarter": "Q2",
        "year": 2025
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": "W. Monroe St.",
    "id": "kuumba_lynx",
    "city_category": "chicago"
  },
  {
    "name": "Window to the World",
    "address": null,
    "city": "Chicago",
    "state": "IL",
    "zip_code": null,
    "category": "Systems Building",
    "grant_amount_awarded": 50000.0,
    "lat": 41.86,
    "lng": -87.665,
    "service_areas": [
      "rogers_park",
      "west_ridge",
      "uptown",
      "lincoln_square",
      "north_center",
      "lake_view",
      "lincoln_park",
      "near_north_side",
      "edison_park",
      "norwood_park",
      "jefferson_park",
      "forest_glen",
      "north_park",
      "albany_park",
      "portage_park",
      "irving_park",
      "dunning",
      "montclare",
      "belmont_cragin",
      "hermosa",
      "avondale",
      "logan_square",
      "humboldt_park",
      "west_town",
      "austin",
      "west_garfield_park",
      "east_garfield_park",
      "near_west_side",
      "north_lawndale",
      "south_lawndale",
      "lower_west_side",
      "loop",
      "near_south_side",
      "armour_square",
      "douglas",
      "oakland",
      "fuller_park",
      "grand_boulevard",
      "kenwood",
      "washington_park",
      "hyde_park",
      "woodlawn",
      "south_shore",
      "chatham",
      "avalon_park",
      "south_chicago",
      "burnside",
      "calumet_heights",
      "roseland",
      "pullman",
      "south_deering",
      "east_side",
      "west_pullman",
      "riverdale",
      "hegewisch",
      "garfield_ridge",
      "archer_heights",
      "brighton_park",
      "mckinley_park",
      "bridgeport",
      "new_city",
      "west_elsdon",
      "gage_park",
      "clearing",
      "west_lawn",
      "chicago_lawn",
      "west_englewood",
      "englewood",
      "greater_grand_crossing",
      "ashburn",
      "auburn_gresham",
      "beverly",
      "washington_heights",
      "mount_greenwood",
      "morgan_park",
      "ohare",
      "edgewater"
    ],
    "service_areas_type": "City Wide",
    "service_areas_count": 77,
    "primary_neighborhood": null,
    "grants": [
      {
        "number": 1,
        "amount_awarded": 50000.0,
        "category": "Systems Building",
        "quarter": "Q4-2024",
        "year": 2024
      }
    ],
    "grant_count": 1,
    "has_multiple_grants": false,
    "location_note": null,
    "id": "window_to_the_world",
    "city_category": "chicago"
  }
];